name: Android CI - Master

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches: 
     - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
    - name: Build with Gradle
      run: sudo ./gradlew build
